# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  test-app:
    docker:
      - image: 056186925767.dkr.ecr.ap-northeast-1.amazonaws.com/ecr-shankar-tool-box/demo-app:edf93f6b-02ad-4cd5-b8f8-8e22dc0e4265
        environment:
          AWS_REGION: ap-northeast-1
          AWS_DEFAULT_REGION: ap-northeast-1
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
          aws_default_region: ap-northeast-1 
         
    steps:
      - setup_remote_docker:
          version: 20.10.17    
      - run:
          name: Build doc
          command: |
            export AWS_REGION=ap-northeast-1         
            #docker pull 056186925767.dkr.ecr.ap-northeast-1.amazonaws.com/ecr-shankar-tool-box/demo-app:edf93f6b-02ad-4cd5-b8f8-8e22dc0e4265
            #docker run --name demo-test -d -p 8080:80 056186925767.dkr.ecr.ap-northeast-1.amazonaws.com/ecr-shankar-tool-box/demo-app:edf93f6b-02ad-4cd5-b8f8-8e22dc0e4265
            sleep 100
            curl http://localhost:8080/

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test-artifact:
    jobs:
      - test-app
  
